### ISSUE TITLE
イベントのプロジェクト体制整備

### ISSUE THREAD

**Issue by kzk-maeda** [aws-startup-community/aws-startup-community-conference-2022#1]
# 背景
- そこそこの規模のイベントになるので、誰が何をメインで動くかを明確にしておいた方が混乱が少なそう

# 案
- Lead
  - とりまとめとかスケジュール管理とかいろいろ
- 登壇者側の担当
  - cfp整理
  - 登壇者コミュニケーション
- 参加者側の担当
  - イベント広報
  - ？？
- 当日オペレーションの担当
  - 担当決め
  - 配信系の調整
  - 懇親イベントの調整

**Comment by mats16** [comment]
自分が他で見てる感じだとこんな感じですかね

- イベント全体統括（とりまとめとかスケジュール管理とかいろいろ）
- 懇親会担当部長

あと、トラック毎（Seed/Early Track と Mid/Later Track）にトラックオーナーがいる事が多いと思いますが、配信周りでトラックごとに4-5人ぐらい欲しいと沼口さんが言っていたので内訳確認しますね（というか相談したほうがいいかも）

- トラックオーナー（CfP採択の最終決定、登壇者連絡等）
- 配信まわり

**Comment by mats16** [comment]
トラックオーナーはエンジニアの方がいいと思うので、所属企業のフェーズ考えると
- Seed/Early Track Owner → @isasenth or @さわら
- Mid/Later Track → @kzk-maeda 

こんな感じ？（勝手に書いてる）
重いロールの兼務は厳しいので
- イベント全体統括 → @sumi-biztech or @さわら

ですかね？（勝手に書いてる）

配信周りは未定ですが、自分と沼口さんでそれぞれ張ろうかなとと思っています。
